[tool.poetry]
name = "caillou"
version = "0.0.1"
description = "AI Assistant in the Command-Line"
authors = ["Sylvain Dudoit <sdudoit@proton.me>"]
license = "GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"
langchain = "^0.1.16"
pypdf = "^4.2.0"

[tool.poetry.group.dev.dependencies]
black = "^24.4.0"
isort = "^5.13.2"
mypy = "^1.9.0"
ruff = "^0.3.7"
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
