[tool.poetry]
name = "caillou"
version = "0.0.1"
description = "AI Assistant in the Command-Line"
authors = ["Sylvain Dudoit <sdudoit@proton.me>"]
license = "GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"
langchain = "^0.1.16"
pypdf = "^4.2.0"
chromadb = "^0.4.24"
python-dotenv = "^1.0.1"
openai = "^1.21.2"
langchain-openai = "^0.1.3"
ruff = "^0.4.0"
textual = "^0.57.1"
clipboard = "^0.0.4"

[tool.poetry.group.dev.dependencies]
black = "^24.4.0"
isort = "^5.13.2"
mypy = "^1.9.0"
pytest = "^8.1.1"
textual-dev = "^1.5.1"

[tool.ruff]
select = ["E", "F", "W", "Q", "I"]
ignore = ["E203"]
fixable = ["ALL"]
unfixable = []
line-length = 180


[tool.mypy]
disallow_untyped_defs = true
show_error_codes = true
no_implicit_optional = true
warn_return_any = true
warn_unused_ignores = true
exclude = ["docs", "tests", "examples", "tools", "build"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

