name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:

  code_quality:
    name: code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: ">=3.11" 
          cache: poetry

      - name: Install Dependencies
        run: poetry install

      - name: Check Linting & Formatting
        run: poetry run ruff check -n --output-format=github caillou/

      - name: Check Type Hinting
        run: poetry run mypy caillou/

  unit_tests:
    name: unit tests
    needs:
      - code_quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: ">=3.11" 
          cache: poetry

      - name: Install Dependencies
        run: poetry install    

      - name: Check Unit Tests
        run: poetry run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=caillou tests/unit_tests/ | tee pytest-coverage.txt

      - name: Add Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        if: always()
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
          

  build:
    name: build
    needs:
      - unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: ">=3.11" 
          cache: poetry

      - name: Install Dependencies
        run: poetry install    

      - name: Check Build
        run: poetry build
